### ISSUE TITLE
Improperly overriding actions/checkout@v2 

### ISSUE THREAD

**Issue by lexiwitch** [mskelton/setup-yarn#1]
This workflow redundantly runs `actions/checkout@v2` and thereby overrides any already-existing checkout step, thus causing problems when `fetch-depth: 0` is required as an argument to `actions/checkout` (for example, in order to deploy to Dokku). Re-running the checkout action means that this action is not composable with other actions and cannot be run as a build step in a larger repository.

**Comment by mskelton** [comment]
If you need to customize the checkout action or can't use this as a result, I'm afraid you will just need to customize it via a fork or by replicating the individual steps.  This is kind of a personal action of mine to remove boilerplate when I setup stuff, and not intended to fit all use cases.
